IPAM Web Application/HMSPortal/Controllers/AuthController.cs
using Confluent.Kafka;
using EchoBot.Model;
using HMS.Infrastructure.Repositories.IRepository;
using HMSPortal.Application.Core.Notification;
using HMSPortal.Application.Core.Notification.Email;
using HMSPortal.Application.ViewModels.Auth;
using HMSPortal.Domain.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using NuGet.Common;
using System;
using System.Numerics;
using System.Text;

namespace HMSPortal.Controllers
{
	public class AuthController : AdminBaseController
    {
		private readonly SignInManager<ApplicationUser> _signInManager;
		private readonly ILogger<AuthController> _logger;
		private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotificatioServices _notificatioServices;
        private readonly IIdentityRespository _identityRespository;

        public AuthController(SignInManager<ApplicationUser> signInManager, ILogger<AuthController> logger, UserManager<ApplicationUser> userManager, INotificatioServices notificatioServices, IIdentityRespository identityRespository)
        {
            _signInManager=signInManager;
            _logger=logger;
            _userManager=userManager;
            _notificatioServices=notificatioServices;
            _identityRespository=identityRespository;
        }

        public async Task<IActionResult> LogOut()
		{
			await _signInManager.SignOutAsync();

			_logger.LogInformation($"User {User.Identity.Name} logged out.");

            return Redirect("/Identity/Account/Login");

		}

        [HttpGet("Dashboard/AccessDenied")]
        public IActionResult AccessDenied(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

		[HttpGet]
        public async Task<IActionResult> ConfirmEmail(string userId, string token, string time)
        {
            if (string.IsNullOrWhiteSpace(userId) || string.IsNullOrWhiteSpace(token) || string.IsNullOrWhiteSpace(time))
            {
                return BadRequest("Invalid email confirmation request.");
            }

            if (!DateTime.TryParse(time, out var emailSentTime))
            {
                return BadRequest("Invalid time format.");
            }

            // Check if the time has exceeded 10 minutes
            //var currentTime = DateTime.UtcNow;
            //var timeDifference = currentTime - emailSentTime;

            //if (timeDifference.TotalMinutes > 10)
            //{
            //    ViewBag.Message = "Expired";
            //    return BadRequest("The email confirmation link has expired.");
            //}


            var user = await _userManager.FindByIdAsync(userId);
         
            if (user == null)
            {
                return NotFound("User not found.");
            }

            if (user.EmailConfirmed)
            {
                if(user.PasswordConfirmed)
                {
                    ViewBag.Message = "Your account has been confirm";
                    return Redirect("/Identity/Account/Login");
                }
                else
                {
                    return RedirectToAction("SetPassword", new { id = user.Id.Base64Encode() }); // Redirect to a confirmation page or any other action

                }
            }
            byte[] decodedBytes = WebEncoders.Base64UrlDecode(token);
            token = Encoding.UTF8.GetString(decodedBytes);

            var result = await _userManager.ConfirmEmailAsync(user, token);
            if (result.Succeeded)
            {
                return RedirectToAction("SetPassword", new {id = user.Id.Base64Encode()}); // Redirect to a confirmation page or any other action
            }
            else
            {
                // Handle errors (e.g., invalid token)
                return BadRequest("Error confirming your email.");
            }


        }


        public async Task<IActionResult> SetPassword(string id)
        {

           var user =  _userManager.Users.FirstOrDefault(x => x.Id == id.Base64Decode());
            if(user == null)
            {
                // Handle errors (e.g., invalid token)
                return BadRequest("Invalid User.");
            }
            var model = new SetPasswordViewModel
            {
                UserId = id,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetPassword(SetPasswordViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                List<string> errorMessages = new List<string>();

                foreach (var error in ModelState)
                {
                    var sss = error.Value.Errors.Select(x => x.ErrorMessage).ToList();
                    errorMessages.AddRange(sss);
                }

                // Combine all error messages into a single message
                string allErrorMessages = string.Join("; ", errorMessages);

                ModelState.AddModelError("error-V", allErrorMessages);
                return View(viewModel);
            }
            viewModel.UserId = viewModel.UserId.Base64Decode();
            var user =  _userManager.Users.FirstOrDefault(x => x.Id == viewModel.UserId); 
            if(user.PasswordConfirmed)
            {
                return RedirectToAction("Index", "Dashboard");
            }
            var resetToken = await _userManager.GeneratePasswordResetTokenAsync(user);
            var result = await _userManager.ResetPasswordAsync(user, resetToken, viewModel.Password);
            if (result.Succeeded)
            {
                // Optionally sign in the user after setting the password
                user.PasswordConfirmed = true;
                await _userManager.UpdateAsync(user);

                _logger.LogInformation($"User:{user.Email} set  password");
                // Using Url.Action
                var loginUrl = _identityRespository.GenerateLink("Dashboard", "Index");
                var messageModel = new DoctorSignupEmailModel
                {
                    SetPasswordLink = loginUrl,
                    LogoUrl = "https://res.cloudinary.com/dukd0jnep/image/upload/v1718523325/ehxwqremdpkwqvshlhhy.jpg",


                };
                Task.Run(async () =>
                {
                    await _notificatioServices.SendDoctorAcountConfirmation(messageModel);
                });


                // Redirect to dashboard or another page upon successful password set
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                ModelState.AddModelError("error-V", "Erroro ccured while setting your password");
                return View(viewModel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> ForgetPassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ForgetPassword(TokenViewModel viewModel)
        {
            var user = await _userManager.FindByEmailAsync(viewModel.Token);
            if(user == null)
            {
                ModelState.AddModelError("error-V", "User does not exist");
                return View(viewModel);
            }
            var emailModel = new DoctorSignupEmailModel
            {
                DoctorName = user.Email,
                To = user.Email,
                LogoUrl = "https://res.cloudinary.com/dukd0jnep/image/upload/v1718523325/ehxwqremdpkwqvshlhhy.jpg",
                SetPasswordLink =  await _identityRespository.GenerateForgtPasswordLinkAsync(user.Email)

            };
            Task.Run(async () =>
            {
                await _notificatioServices.SendForgetPasswordEmail(emailModel);

            });

            return RedirectToAction( actionName: "Message", controllerName: "Dashboard", new
            {
                title = "Password Reset",
                message = "A password reset link has been sent to the email provided.",
                controller = "Home",
                action ="Index",
                button = "Home"

            });
        }

        [HttpGet]
        public async Task<IActionResult> ResetPassword(string userId, string token, string time)
        {
            var isValidToken = _identityRespository.IsValideToken(token.Base64Decode());
            if (isValidToken)
            {
                return BadRequest("Invalid token or token has been used");
            }

            var user = _userManager.Users.FirstOrDefault(x => x.Id == userId.Base64Decode());
            if (user == null)
            {
                // Handle errors (e.g., invalid token)
                return BadRequest("Invalid User.");
            }
            var model = new SetPasswordViewModel
            {
                UserId = userId,
                Token = token,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetPassword(SetPasswordViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                List<string> errorMessages = new List<string>();

                foreach (var error in ModelState)
                {
                    var sss = error.Value.Errors.Select(x => x.ErrorMessage).ToList();
                    errorMessages.AddRange(sss);
                }

                // Combine all error messages into a single message
                string allErrorMessages = string.Join("; ", errorMessages);

                ModelState.AddModelError("error-V", allErrorMessages);
                return View(viewModel);
            }
          
            viewModel.UserId = viewModel.UserId.Base64Decode();
            var user = _userManager.Users.FirstOrDefault(x => x.Id == viewModel.UserId);
            

 

IPAM Web Application/HMSPortal/Controllers/NotificationController.cs
using HMS.Infrastructure.Persistence.DataContext;
using HMSPortal.Application.AppServices.IServices;
using HMSPortal.Application.Core.Notification;
using HMSPortal.Application.ViewModels.Notification;
using HMSPortal.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HMSPortal.Controllers
{
	public class NotificationController : Controller
	{
        private readonly ApplicationDbContext _context;
        private readonly INotificatioServices notificatioServices;
        private readonly IJobScheduleService _jobScheduleService;
        private readonly UserManager<ApplicationUser> _userManager;

        public NotificationController(ApplicationDbContext context, INotificatioServices notificatioServices, IJobScheduleService jobScheduleService, UserManager<ApplicationUser> userManager)
        {
            _context=context;
            this.notificatioServices=notificatioServices;
            _jobScheduleService=jobScheduleService;
            _userManager=userManager;
        }

        [Authorize]
        public async Task <IActionResult> Index()
        {
            var user =  await _userManager.GetUserAsync(User);
            var notifications = _context.Notifications.Where(x => x.UserId == user.Id)
                .Select(x=> new AllNotificationViewModel
                {
                    Id = x.Id,
                    Message = x.Message,
                    Date = DateTime.Now,
                    Status = x.Status
                }).ToList();
            return View(notifications);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        
        [Authorize]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Add(CreateNotificationViewmodel model)
		{
            if (ModelState.IsValid)
            {
                try
                {
                    DateTime selectedDate = model.Date;
                    int selectedHour = model.Hour;
                    int selectedMinute = model.Minute;

                    // Combine date, hour, and minute to create a DateTime object
                    DateTime notificationDateTime = new DateTime(
                        selectedDate.Year,
                        selectedDate.Month,
                        selectedDate.Day,
                        selectedHour,
                        selectedMinute,
                        0 // seconds
                    );

                    // Ensure the datetime is in the future
                    if (notificationDateTime <= DateTime.Now)
                    {
                        ModelState.AddModelError("error-V", "The selected time must be in the future.");
                        return View(model);
                    }
					var user = await _userManager.GetUserAsync(User);
                    var notifications = _context.Notifications.Where(x => x.UserId == user.Id);

					model.Date = notificationDateTime;
                    model.NotificationTime = notificationDateTime;
                    model.UserId = user.Id;
                    await _jobScheduleService.ScheduleNotification(model);

                    TempData["Success"] = "Notification created successfully.";
                    return RedirectToAction(nameof(Index), "Notification");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("error-V", $"An error occurred while creating the notification: {ex.Message}");
                }
            }
			

			return View(model);
        }
    }
}

IPAM Web Application/HMSPortal/Controllers/PaymentController.cs
using HMS.Infrastructure.Repositories.IRepository;
using HMSPortal.Application.AppServices.IServices;
using HMSPortal.Application.ViewModels;
using HMSPortal.Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.EntityFrameworkCore.Metadata.Internal;
//using HMSPortal.Domain.Enums;

namespace HMSPortal.Controllers
{
	public class PaymentController : Controller
	{
		private readonly IDoctorServices _doctorServices;

        public PaymentController(IDoctorServices doctorServices)
        {
            _doctorServices=doctorServices;
        }

        public async Task<IActionResult> Index()
		{
            await _doctorServices.CreateDoctor(GenerateFakeDoctor());
			return View();
		}


        private static IFormFile CreateFakeImage()
        {
            var content = "This is a fake file content";
            var fileName = "doctor-image.jpg";
            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);
            writer.Write(content);
            writer.Flush();
            stream.Position = 0;

            return new FormFile(stream, 0, stream.Length, "image", fileName);
        }
        public static AddDoctorViewModel GenerateFakeDoctor()
        {
            var random = new Random();

            return new AddDoctorViewModel
            {
                FirstName = "John",
                LastName = "Doe",
                Email = DateTime.Now.Ticks.ToString()+ ".doe@example.com",
                Phone = "1234567890",
                PostalCode = "12345",
                HouseNumber = "42",
                Address = "123 Main St, Anytown, USA",
                DateOfBirth = DateTime.Now.AddYears(-35).AddDays(-random.Next(365)),
                Gender = random.Next(2) == 0 ? "Male" : "Female",
                DoctorCode = "DOC" + random.Next(1000, 9999).ToString(),
                BackgroundHistory = "Graduated from Medical University with honors. Residency at City Hospital.",
                Specialty = "Cardiology",
                YearsOfExperience = random.Next(1, 20),
                Age = 35,
                DoctorDetails = "Specializes in non-invasive cardiac procedures. Published research on heart disease prevention.",
                Image = CreateFakeImage(),
                Password = "P@ssw0rd123!",
                ImageUrl = "https://example.com/doctor-image.jpg"
            };
        }

        // Assuming you have the necessary using statements for your project

  

}


}

IPAM Web Application/HMSPortal/Views/Shared/_Layout.cshtml
@using HMS.Infrastructure.Persistence.DataContext
@using HMSPortal.Application.Core
@using HMSPortal.Application.Core.Cache
@using HMSPortal.Application.Core.Extensions
@using HMSPortal.Application.ViewModels
@using HMSPortal.Domain.Enums
@using HMSPortal.Domain.Models
@using Microsoft.AspNetCore.Identity
@using Microsoft.Extensions.Caching.Memory
@using Newtonsoft.Json
@using System.Security.Claims
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@inject   IHttpContextAccessor _httpContextAccessor;
@inject RoleManager<IdentityRole> _roleManager;
@inject  IMemoryCache _memoryCache;

@{
	var cacheKey = CoreValiables.LoginUser;
	var userCache = new CacheUserModel();
	var superAdminName = Roles.SuperAdmin.ToString();
	var adminName = Roles.Admin.ToString();
	var doctorName = Roles.Doctor.ToString();
	var PatientName = Roles.Patient.ToString();
	string idValue = "";
	var successMessage = TempData["Success"] as string;

	var user = _httpContextAccessor.HttpContext.User;
	var userName = user.FindFirst(ClaimTypes.Role)?.Value;
	// var cssacheKey = user.Claims.FirstOrDefault();
	// var userCacheString = _httpContextAccessor.HttpContext.Session.GetString(cacheKey);
	// IList <string> roles = new List<string>();

	// if (string.IsNullOrEmpty(userCacheString))
	// {
		
	// 	if (user.Identity.IsAuthenticated)
	// 	{
	// 		var currentUser = await UserManager.GetUserAsync(user);
	// 		if (currentUser != null)
	// 		{
	// 			roles =  await UserManager.GetRolesAsync(currentUser);
	// 			userCache = new CacheUserModel
	// 					{
	// 						Id = currentUser.Id,
	// 						Email = currentUser.Email,
	// 						Role = roles.FirstOrDefault()

	// 					};

	// 		}

	// 	}
	// 	else
	// 	{
	// 		// var currentUser = UserManager.Users.FirstOrDefault(x => x.Email == "ozougwuifeanyi160@gmail.com");
	// 		// roles =  await UserManager.GetRolesAsync(currentUser);
	// 		userCache = JsonConvert.DeserializeObject<CacheUserModel>(userCacheString);
	// 	}

	// 	// Serialize userCache to a JSON string
	// 	var userCacheString1 = JsonConvert.SerializeObject(userCache);
	// 	// Store userCacheString in session
	// 	_httpContextAccessor.HttpContext.Session.SetString(cacheKey, userCacheString1);



	// }
	// else
	// {
	// 	userCache = JsonConvert.DeserializeObject<CacheUserModel>(userCacheString);
	// }

	// idValue = userCache.Id;
	var leftBarPartialView = "";


}


<!DOCTYPE html>
<html lang="en">

<head>
	<base href="/" />
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Medi smart appointment system</title>
	<!-- Fav  Icon Link -->
	<link rel="shortcut icon" type="image/png" href="mediplus-lite/img/logo3.png">
	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<!-- themify icons CSS -->
	<link rel="stylesheet" href="css/themify-icons.css">
	<!-- Animations CSS -->
	<link rel="stylesheet" href="css/animate.css">
	<!-- Main CSS -->
	<link rel="stylesheet" href="css/styles.css">
	<link rel="stylesheet" href="css/red.css" id="style_theme">
	<link rel="stylesheet" href="css/responsive.css">
	<!-- morris charts -->
	<link rel="stylesheet" href="charts/css/morris.css">
	<!-- jvectormap -->
	<link rel="stylesheet" href="css/jquery-jvectormap.css">

	<script src="js/modernizr.min.js"></script>
	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

</head>

<body>

	<div class="theme-settings" id="switcher">
		<span class="theme-click">
			<span class="ti-settings"></span>
		</span>
		<span class="theme-color theme-default" data-color="green"></span>
		<span class="theme-color theme-blue" data-color="blue"></span>
		<span class="theme-color theme-red theme-active" data-color="red"></span>
		<span class="theme-color theme-violet" data-color="blue"></span>
		<span class="theme-color theme-yellow" data-color="yellow"></span>
	</div>

	<div class="wrapper">
		<!-- Sidebar -->
		<nav id="sidebar" class="proclinic-bg">
			<div class="sidebar-header">
				<a asp-controller="Dashboard" asp-action="Index"><img src="mediplus-lite/img/logo3.png" class="logo" alt="logo"></a>
			</div>
			@{
				var role = user.FindFirst(ClaimTypes.Role)?.Value;

				switch (role)
				{
					case var _ when role == PatientName:
						@await Html.PartialAsync("_patientLeftBarPartial ")
						;
						break;

					case var _ when role == doctorName:
						@await Html.PartialAsync("_doctorAdmiLeftBarPartial")
						;
						break;

					// Add more cases if there are other roles
					default:
						// Optional: handle the default case if no roles match
						@await Html.PartialAsync("_superAdmiLeftBarPartial")
						break;
				}
			}


			<div class="nav-help animated fadeIn">
				<h5><span class="ti-comments"></span> Need Help</h5>
				<h6>
					<span class="ti-mobile"></span> +1 1234 567 890
				</h6>
				<h6>
					<span class="ti-email"></span> suppoer@medismart.com
				</h6>
				<p class="copyright-text">Copy rights &copy; 2024</p>
			</div>
		</nav>
		<!-- /Sidebar -->
		<!-- Page Content -->
		<div id="content">
			<!-- Top Navigation -->
			<nav class="navbar navbar-default">
				<div class="container-fluid">
					<div class="responsive-logo">
						<a href="index.html"><img src="images/logo-dark.png" class="logo" alt="logo"></a>
					</div>
					<ul class="nav">
						<li class="nav-item">
							<span class="ti-menu" id="sidebarCollapse"></span>
						</li>
						<li class="nav-item">
							<span title="Fullscreen" class="ti-fullscreen fullscreen"></span>
						</li>
						<li class="nav-item">
							<a data-toggle="modal" data-target=".proclinic-modal-lg">
								<span class="ti-search"></span>
							</a>
							<div class="modal fade proclinic-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
								<div class="modal-dialog modal-lorvens">
									<div class="modal-content proclinic-box-shadow2">
										<div class="modal-header">
											<h5 class="modal-title">Search Patient/Doctor:</h5>
											<span class="ti-close" data-dismiss="modal" aria-label="Close">
											</span>
										</div>
										<div class="modal-body">
											<form>
												<input id="userid" hidden="hidden" value="@idValue" />
												<div class="form-group">
													<input type="text" class="form-control" id="search-term" placeholder="Type text here">
													<button type="button" class="btn btn-lorvens proclinic-bg">
														<span class="ti-location-arrow"></span> Search
													</button>
												</div>
											</form>
										</div>
									</div>
								</div>
							</div>
						</li>
						<li class="nav-item">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
								<span class="ti-announcement"></span>
							</a>
							<div class="dropdown-menu proclinic-box-shadow2 notifications animated flipInY">
								<h5>Notifications</h5>
								<a class="dropdown-item" href="#">
									<span class="ti-wheelchair"></span> New Patient Added
								</a>
								<a class="dropdown-item" href="#">
									<span class="ti-money"></span> Patient payment done
								</a>
								<a class="dropdown-item" href="#">
									<span class="ti-time"></span>Patient Appointment booked
								</a>
								<a class="dropdown-item" href="#">
									<span class="ti-wheelchair"></span> New Patient Added
								</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
								<span class="ti-user"></span>
							</a>
							<div class="dropdown-menu proclinic-box-shadow2 profile animated flipInY">
								@if (User != null && User.Identity.IsAuthenticated)
								{
									<h5> @User.Identity.Name!</h5>
								}

								<a class="dropdown-item" href="#">
									<span class="ti-settings"></span> Settings
								</a>
								<a class="dropdown-item" href="#">
									<span class="ti-help-alt"></span> Help
								</a>
								<a class="dropdown-item" asp-action="LogOut" asp-controller="Auth">
									<span class="ti-power-off"></span> Logout
								</a>
							</div>
						</li>
					</ul>

				</div>
			</nav>
			<div class="row no-margin-padding">
				<div class="col-md-6">
					<h3 class="block-title">@ViewData["Title"]</h3>
				</div>
				<div class="col-md-6">
					<ol class="breadcrumb">
						<li class="breadcrumb-item">
							<a asp-action="Index" asp-controller="Dashboard">
								<span class="ti-home"></span>
							</a>
						</li>
						<li class="breadcrumb-item">@Html.GetControllerDisplayName()</li>
						<li class="breadcrumb-item active">@ViewData["Title"]</li>
						@if (!string.IsNullOrEmpty(successMessage))
						{

							<div class="alert alert-info alert-dismissible fade show" role="alert">
								<strong>@successMessage</strong>
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">×</span>
								</button>
							</div>
						}
					</ol>
				</div>
			</div>
		

			@RenderBody()

		</div>
		<!-- /Page Content -->
	</div>
	<!-- Back to Top -->
	<!-- /Back to Top -->
	<!-- Jquery Library-->
	<script src="js/jquery-3.2.1.min.js"></script>
	<!-- Popper Library-->
	<script src="js/popper.min.js"></script>
	<!-- Bootstrap Library-->
	<script src="js/bootstrap.min.js"></script>
	<!-- morris charts -->
	<script src="charts/js/raphael-min.js"></script>
	<script src="charts/js/morris.min.js"></script>
	<script src="js/custom-morris.js"></script>
	<script src="js/modernizr.min.js"></script>

	<script>
		function reloadPage() {
			location.reload();
		}
	</script>

	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
	<script src="js/custom.js"></script>
	<script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
	<script src="https://cdn.tiny.cloud/1/d1fpkxihlzdu61yllazo0c9ehlxeuk04a3awulg82m1vo2b4/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.18/signalr.min.js"></script>
@* 	<script>
		var connection = new signalR.HubConnectionBuilder().withUrl("/userHub").build();

		connection.on("ForceLogout", function (userId) {
			// Redirect to access denied page
			var userid = document.getElementById('userid').value;

			console.log(userId);

			if (userId == userid)
			{
				
				window.location.href = '/Auth/LogOut';
			}
				
		});

		connection.start().catch(function (err) {
			return console.error(err.toString());
		});
	</script> *@
</body>
</html>
@RenderSection("Scripts", required: false)

IPAM Web Application/HMSPortal/Views/Shared/_patientLeftBarPartial .cshtml
<ul class="list-unstyled components">
	<li class="active">
		<a asp-action="Index" asp-controller="Dashboard" data-toggle="collapse" aria-expanded="true">
			<span class="ti-home"></span> Home
		</a>

	</li>
	
	<li>
		<a href="#nav-patients" data-toggle="collapse" aria-expanded="false">
			<span class="ti-wheelchair"></span> Notifications
		</a>
		<ul class="collapse list-unstyled" id="nav-patients">


			<li>
				<a asp-controller="Notification" asp-action="Index">Notifications</a>
			</li>
			@* <li>
				<a asp-controller="Patient" asp-action="Index">All Patients</a>
			</li> *@


		</ul>

	</li>

	<li>
		<a href="#nav-appointment" data-toggle="collapse" aria-expanded="false">
			<span class="ti-pencil-alt"></span>My Appointments
		</a>
		<ul class="collapse list-unstyled" id="nav-appointment">
			<li>
				<a asp-controller="Appointment" asp-action="PatientAppointment"> Book Appointment</a>
			</li>
			<li>
				<a asp-controller="Appointment" asp-action="MyAppointments">My Appointments</a>
			</li>
			
		</ul>
	</li>
	<li>
		<a href="#nav-payment" data-toggle="collapse" aria-expanded="false">
			<span class="ti-money"></span> Settings
		</a>
		<ul class="collapse list-unstyled" id="nav-payment">
			@* <li>
			<a href="add-payment.html">Add Payment</a>
			</li> *@
			<li>
				<a asp-controller="Payment" asp-action="Upsert">Add Payment</a>
			</li>
			<li>
				<a asp-controller="Payment" asp-action="Index">All Payment</a>
			</li>

			@* <li>
			<a href="payments.html">All Payments</a>
			</li> *@
			@* <li>
			<a href="about-payment.html"></a>
			</li> *@
			<li>
				<a asp-controller="PaymentInvoice" asp-action="Detail">Payment Invoice</a>
			</li>
		</ul>
	</li>
	

	
</ul>